[features]
resolution = true
skip-lint = false

[programs.localnet]
reputation = "4GjB4xdm1VTPVM6KSiEEfJpD4u7BfY1qDx77StiFShvQ"
credit_vault = "EsykPsafhHUeN7jA9DGqBiGuBsTBaFynLDVVpE4jFXDg"

[programs.devnet]
reputation = "4GjB4xdm1VTPVM6KSiEEfJpD4u7BfY1qDx77StiFShvQ"
credit_vault = "EsykPsafhHUeN7jA9DGqBiGuBsTBaFynLDVVpE4jFXDg"

[programs.mainnet]
reputation = "4GjB4xdm1VTPVM6KSiEEfJpD4u7BfY1qDx77StiFShvQ"
credit_vault = "EsykPsafhHUeN7jA9DGqBiGuBsTBaFynLDVVpE4jFXDg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --all -- --nocapture"
